import type { MetricRegistryEntry } from "@/lib/admin/officeAudit/types";

/**
 * Machine-readable registry for every Office home-dashboard metric.
 * Application paths reflect the real implementation discovered in code review.
 */
export const OFFICE_METRIC_REGISTRY: MetricRegistryEntry[] = [
  {
    metricId: "ops.total_bookings_today",
    uiLabel: "Total bookings today",
    pageSection: "todays_operations",
    testId: "office-metric-ops-total",
    valueKind: "integer",
    uiFormattingRule: "integer tabular",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.total",
      helper: "computeOfficeTodayScheduleStats",
      notes: "Operational total excluding cancelled/failed/payment_expired",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status", "cleaner_id", "team_id"],
      filters: "date = :auditYmd",
      joins: "booking_cleaners (assignment confirmation)",
      notes: "Schedule date column is bookings.date (text), not booking_date",
    },
    authoritativeCalculationId: "db.schedule.total",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Count of non-terminal bookings where bookings.date equals the selected Johannesburg calendar day. Terminal = cancelled|failed|payment_expired.",
  },
  {
    metricId: "ops.completed",
    uiLabel: "Completed",
    pageSection: "todays_operations",
    testId: "office-metric-ops-completed",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.completed",
      helper: "computeOfficeTodayScheduleStats",
      notes: "status = completed",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd AND lower(status) = 'completed'",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.completed",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Visit-day rows with status completed.",
  },
  {
    metricId: "ops.in_progress",
    uiLabel: "In progress",
    pageSection: "todays_operations",
    testId: "office-metric-ops-in-progress",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.inProgress",
      helper: "computeOfficeTodayScheduleStats",
      notes: "status in (in_progress, en_route)",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd AND lower(status) IN ('in_progress','en_route')",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.in_progress",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Visit-day rows currently in_progress or en_route.",
  },
  {
    metricId: "ops.upcoming",
    uiLabel: "Upcoming",
    pageSection: "todays_operations",
    testId: "office-metric-ops-upcoming",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.upcoming",
      helper: "computeOfficeTodayScheduleStats",
      notes: "Non-terminal, non-active, with confirmed assignment",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status", "cleaner_id", "team_id"],
      filters: "date = :auditYmd AND not terminal/active AND has assignment",
      joins: "booking_cleaners",
      notes: "selected_cleaner_id alone is NOT assignment",
    },
    authoritativeCalculationId: "db.schedule.upcoming",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Open visit-day bookings that are not in progress and have cleaner_id OR team_id OR booking_cleaners roster rows.",
  },
  {
    metricId: "ops.unassigned",
    uiLabel: "Unassigned",
    pageSection: "todays_operations",
    testId: "office-metric-ops-unassigned",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.unassigned",
      helper: "computeOfficeTodayScheduleStats",
      notes: "Day schedule unassigned — not the fleet Needs Action unassigned count",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status", "cleaner_id", "team_id", "selected_cleaner_id"],
      filters: "date = :auditYmd AND open AND no confirmed assignment",
      joins: "booking_cleaners",
      notes: "Preferred-only (selected_cleaner_id) counts as unassigned",
    },
    authoritativeCalculationId: "db.schedule.unassigned",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Open visit-day bookings without cleaner_id, team_id, or booking_cleaners rows.",
  },
  {
    metricId: "ops.cancelled_excluded",
    uiLabel: "cancelled / expired excluded",
    pageSection: "todays_operations",
    testId: "office-metric-ops-cancelled-excluded",
    valueKind: "integer",
    uiFormattingRule: "integer; shown only when > 0",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.cancelled",
      helper: "computeOfficeTodayScheduleStats",
      notes: "cancelled + failed + payment_expired",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd AND lower(status) IN ('cancelled','failed','payment_expired')",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.cancelled",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Terminal rows excluded from operational total.",
  },
  {
    metricId: "ops.payments_received_today",
    uiLabel: "Payments received today",
    pageSection: "todays_operations",
    testId: "office-metric-ops-payments-received-today",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA}",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "revenueTodayZar",
      helper: "fetchAdminDashboardRevenueSummary / computeAdminDashboardRevenueSummary",
      notes: "Payment-day bucket via payment_completed_at — NOT visit date",
    },
    databaseSource: {
      table: "bookings",
      columns: [
        "payment_status",
        "payment_completed_at",
        "status",
        "amount_paid_cents",
        "total_paid_zar",
        "refunded_at",
        "refund_status",
        "billing_type",
        "is_monthly_billing_booking",
        "monthly_invoice_id",
      ],
      filters:
        "payment_status='success' AND payment_completed_at in JHB today AND eligible (not refunded/terminal/monthly child)",
      joins: "none — public.payments does not exist; ledger payment_transactions not used for home revenue",
      notes: "Amount = amount_paid_cents if >0 else total_paid_zar*100",
    },
    authoritativeCalculationId: "db.revenue.today_zar",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Sum of eligible booking payments whose payment_completed_at falls in [today 00:00+02:00, tomorrow). Rounded to whole ZAR.",
  },
  {
    metricId: "ops.paid_by_payment_time",
    uiLabel: "paid by payment time",
    pageSection: "todays_operations",
    testId: "office-metric-ops-paid-by-payment-time",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "paidBookingsToday",
      helper: "computeAdminDashboardRevenueSummary",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["payment_status", "payment_completed_at"],
      filters: "same eligibility as payments received today",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.today_count",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Count of revenue-eligible bookings paid today by payment_completed_at.",
  },
  {
    metricId: "ops.visit_paid_value",
    uiLabel: "Visit paid value",
    pageSection: "todays_operations",
    testId: "office-metric-ops-visit-paid-value",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA}; hidden when finance payload absent",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "finance.paidValueZar",
      helper: "computeOfficeVisitDayFinance",
      notes: "Visit-date paid value; monthly children excluded",
    },
    databaseSource: {
      table: "bookings",
      columns: [
        "date",
        "status",
        "payment_status",
        "payment_completed_at",
        "amount_paid_cents",
        "total_paid_zar",
        "monthly_invoice_id",
        "is_monthly_billing_booking",
        "billing_type",
        "refunded_at",
        "refund_status",
      ],
      filters: "date = :auditYmd AND not terminal AND revenue-eligible AND not monthly child",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.visit_finance.paid_value_zar",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Sum of revenue-eligible paid amounts for visit-date rows (service day), excluding monthly invoice children.",
  },
  {
    metricId: "action.unassigned",
    uiLabel: "Unassigned bookings",
    pageSection: "needs_action",
    testId: "office-metric-action-unassigned-count",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/ops-snapshot",
      responsePath: "unassigned",
      helper: "computeOpsSnapshotFromRows / classifyAttentionQueue",
      notes: "Fleet-wide exclusive queue — not today's schedule unassigned",
    },
    databaseSource: {
      table: "bookings",
      columns: [
        "status",
        "date",
        "time",
        "cleaner_id",
        "team_id",
        "dispatch_status",
        "total_paid_zar",
        "amount_paid_cents",
        "is_recurring_generated",
        "is_monthly_billing_booking",
        "billing_type",
        "monthly_invoice_id",
        "recurring_id",
        "payment_status",
      ],
      filters:
        "status NOT IN (completed,cancelled,failed,payment_expired,pending_payment) AND no cleaner/team AND (paid OR recurring/monthly assignable) AND not SLA/unassignable higher priority",
      joins: "none (ops ignores booking_cleaners roster)",
      notes: "Priority: sla > unassignable > unassigned > starting-soon",
    },
    authoritativeCalculationId: "db.ops.unassigned",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Open fleet bookings with no cleaner_id/team_id that are paid or recurring/monthly assignable, and not classified as SLA or unassignable.",
  },
  {
    metricId: "action.starting_within_2h",
    uiLabel: "Starting within 2 hours",
    pageSection: "needs_action",
    testId: "office-metric-action-starting-soon-count",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/ops-snapshot",
      responsePath: "startingSoon",
      helper: "classifyAttentionQueue",
      notes: "startsIn in [0, 120) minutes; unpaid non-recurring only (else unassigned)",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "time", "status", "cleaner_id", "team_id", "dispatch_status"],
      filters: "open, no assignment, not sla/unassignable/unassigned, start within 2h",
      joins: "none",
      notes: "Start instant = date + time +02:00",
    },
    authoritativeCalculationId: "db.ops.starting_soon",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Unassigned open bookings starting in [0,120) minutes that failed the paid/recurring unassigned gate.",
  },
  {
    metricId: "action.sla_breaches",
    uiLabel: "SLA breaches",
    pageSection: "needs_action",
    testId: "office-metric-action-sla-count",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/ops-snapshot",
      responsePath: "slaBreaches",
      helper: "isSlaBreachRow",
      notes: "DISPATCH_SLA_BREACH_MINUTES default 10",
    },
    databaseSource: {
      table: "bookings",
      columns: ["status", "cleaner_id", "team_id", "dispatch_status", "became_pending_at", "created_at"],
      filters:
        "status=pending AND no assignment AND dispatch_status in (searching,offered) AND coalesce(became_pending_at,created_at) < now - slaMinutes",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.ops.sla_breaches",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Pending dispatch rows past the SLA clock without assignment.",
  },
  {
    metricId: "action.unassignable",
    uiLabel: "Unassignable",
    pageSection: "needs_action",
    testId: "office-metric-action-unassignable-count",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/ops-snapshot",
      responsePath: "unassignable",
      helper: "classifyAttentionQueue",
      notes: "dispatch_status=unassignable and no assignment; after SLA check",
    },
    databaseSource: {
      table: "bookings",
      columns: ["status", "dispatch_status", "cleaner_id", "team_id"],
      filters: "open AND dispatch_status=unassignable AND no assignment AND not SLA",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.ops.unassignable",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Open bookings marked unassignable without a cleaner/team.",
  },
  {
    metricId: "schedule.total",
    uiLabel: "Total",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-total",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.total",
      helper: "computeOfficeTodayScheduleStats",
      notes: "Same as ops.total_bookings_today",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd operational",
      joins: "booking_cleaners",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.total",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same operational total as Today's operations.",
  },
  {
    metricId: "schedule.completed",
    uiLabel: "Completed",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-completed",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.completed",
      helper: "computeOfficeTodayScheduleStats",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd AND status=completed",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.completed",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same completed count as Today's operations.",
  },
  {
    metricId: "schedule.in_progress",
    uiLabel: "In progress",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-in-progress",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.inProgress",
      helper: "computeOfficeTodayScheduleStats",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status"],
      filters: "date = :auditYmd AND status in (in_progress,en_route)",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.in_progress",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same in-progress count as Today's operations.",
  },
  {
    metricId: "schedule.upcoming",
    uiLabel: "Upcoming",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-upcoming",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.upcoming",
      helper: "computeOfficeTodayScheduleStats",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status", "cleaner_id", "team_id"],
      filters: "assigned open visit-day",
      joins: "booking_cleaners",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.upcoming",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same upcoming count as Today's operations.",
  },
  {
    metricId: "schedule.unassigned",
    uiLabel: "Unassigned",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-unassigned",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "summary.unassigned",
      helper: "computeOfficeTodayScheduleStats",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["date", "status", "cleaner_id", "team_id"],
      filters: "unassigned open visit-day",
      joins: "booking_cleaners",
      notes: "",
    },
    authoritativeCalculationId: "db.schedule.unassigned",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same day-schedule unassigned count as Today's operations.",
  },
  {
    metricId: "schedule.row_status_rules",
    uiLabel: "booking status shown on each row",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-row-status",
    valueKind: "integer",
    uiFormattingRule: "count of rows whose presented status matches independent rules",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "bookings[*] via officeScheduleStatusPresentation",
      helper: "officeScheduleStatusPresentation",
      notes: "UI shows first 8 rows sorted by time",
    },
    databaseSource: {
      table: "bookings",
      columns: ["status", "cleaner_id", "team_id", "selected_cleaner_id"],
      filters: "date = :auditYmd",
      joins: "booking_cleaners",
      notes: "Compared as mismatch count = 0",
    },
    authoritativeCalculationId: "db.schedule.row_status_mismatch_count",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Independent status labels (Done / In progress / Preferred / Unassigned / Assigned / …) must match application presentation for every visit-day row.",
  },
  {
    metricId: "schedule.row_assignment_rules",
    uiLabel: "cleaner or team assignment shown on each row",
    pageSection: "todays_schedule",
    testId: "office-metric-schedule-row-assignment",
    valueKind: "integer",
    uiFormattingRule: "count of assignment-label mismatches (0 = pass)",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "bookings[*] via officeScheduleAssignedCleanerLabel",
      helper: "officeScheduleAssignedCleanerLabel",
      notes: "Labels redacted in reports; compare presence/kind only",
    },
    databaseSource: {
      table: "bookings",
      columns: ["cleaner_id", "team_id", "selected_cleaner_id"],
      filters: "date = :auditYmd",
      joins: "booking_cleaners, cleaners",
      notes: "Kinds: team | roster | confirmed | preferred | none",
    },
    authoritativeCalculationId: "db.schedule.row_assignment_mismatch_count",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Assignment kind derived from team_id / roster / cleaner_id / selected_cleaner_id must match application label kind for every visit-day row.",
  },
  {
    metricId: "capacity.active_workforce",
    uiLabel: "Active workforce",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-active",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "cleaners.length → computeOfficeScheduleCleanerStats.total",
      helper: "computeOfficeScheduleCleanerStats",
      notes: "Active cleaners: is_active is null OR true",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["is_active"],
      filters: "is_active IS NULL OR is_active = true",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.capacity.total",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Count of active cleaners on the roster returned by schedule/day.",
  },
  {
    metricId: "capacity.available_now",
    uiLabel: "Available now",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-available-now",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "computeOfficeScheduleCleanerStats.availableIdle",
      helper: "computeOfficeScheduleCleanerStats / deriveCleanerAvailabilityState",
      notes: "stateKey === online",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["is_available", "status", "availability_weekdays", "is_active"],
      filters: "active cleaners; state online after precedence matrix",
      joins: "bookings (in_progress/en_route/assigned/confirmed for day)",
      notes: "browserOnline approximated as status !== 'offline'",
    },
    authoritativeCalculationId: "db.capacity.available_idle",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Active cleaners with stateKey online after offline→paused→in-job→off-today→booked→online precedence.",
  },
  {
    metricId: "capacity.available",
    uiLabel: "Available",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-available",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "computeOfficeScheduleCleanerStats.availableIdle",
      helper: "computeOfficeScheduleCleanerStats",
      notes: "Same value as Available now (segment vs callout)",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["is_available", "status", "availability_weekdays"],
      filters: "stateKey=online",
      joins: "bookings",
      notes: "",
    },
    authoritativeCalculationId: "db.capacity.available_idle",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Breakdown segment 'Available' equals Available now.",
  },
  {
    metricId: "capacity.booked_or_in_job",
    uiLabel: "Booked / in job",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-busy",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "computeOfficeScheduleCleanerStats.busy",
      helper: "computeOfficeScheduleCleanerStats",
      notes: "stateKey booked|in-job",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["id"],
      filters: "active; has in_progress/en_route or assigned/confirmed roster job today",
      joins: "bookings + booking_cleaners",
      notes: "",
    },
    authoritativeCalculationId: "db.capacity.busy",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Cleaners in-job or booked for the selected day.",
  },
  {
    metricId: "capacity.off_today",
    uiLabel: "Off today",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-off-today",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "computeOfficeScheduleCleanerStats.offToday",
      helper: "computeOfficeScheduleCleanerStats",
      notes: "roster weekday gate",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["availability_weekdays", "is_available", "status"],
      filters: "stateKey=off-today",
      joins: "bookings",
      notes: "Weekday of dateYmd at +02:00",
    },
    authoritativeCalculationId: "db.capacity.off_today",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Online willing cleaners whose availability_weekdays exclude the selected weekday.",
  },
  {
    metricId: "capacity.offline_or_paused",
    uiLabel: "Offline / paused",
    pageSection: "cleaner_capacity",
    testId: "office-metric-capacity-offline",
    valueKind: "integer",
    uiFormattingRule: "integer",
    applicationSource: {
      endpoint: "/api/admin/schedule/day",
      responsePath: "computeOfficeScheduleCleanerStats.manuallyUnavailable",
      helper: "computeOfficeScheduleCleanerStats",
      notes: "paused|offline",
    },
    databaseSource: {
      table: "cleaners",
      columns: ["is_available", "status"],
      filters: "status='offline' OR is_available=false (after offline precedence)",
      joins: "none",
      notes: "status!=='offline' used as browserOnline proxy",
    },
    authoritativeCalculationId: "db.capacity.manually_unavailable",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Cleaners offline (status) or manually paused (is_available=false).",
  },
  {
    metricId: "revenue.receivables_exposure",
    uiLabel: "Receivables exposure",
    pageSection: "revenue_and_receivables",
    testId: "office-metric-revenue-receivables-exposure",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA}",
    applicationSource: {
      endpoint: "client sum of dashboard-stats fields",
      responsePath: "revenueTodayZar + paymentsSnapshot.pendingZar + paymentsSnapshot.overdueZar",
      helper: "office/page.tsx cashTotal",
      notes: "Not bank cash",
    },
    databaseSource: {
      table: "bookings + monthly_invoices",
      columns: ["payment_completed_at", "amount_paid_cents", "balance_cents", "status", "is_overdue"],
      filters: "payment-day revenue + pending_payment bookings + overdue invoices",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.receivables_exposure_zar",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Client-side sum: payments received today + pending booking quotes + overdue monthly invoice balances.",
  },
  {
    metricId: "revenue.payments_received_today",
    uiLabel: "Payments received today",
    pageSection: "revenue_and_receivables",
    testId: "office-metric-revenue-payments-received-today",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA} (bar segment uses raw number; label is ZAR)",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "revenueTodayZar",
      helper: "computeAdminDashboardRevenueSummary",
      notes: "Same underlying value as ops.payments_received_today",
    },
    databaseSource: {
      table: "bookings",
      columns: ["payment_completed_at", "amount_paid_cents", "total_paid_zar"],
      filters: "payment-day eligible",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.today_zar",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same payment-day revenue as Today's operations.",
  },
  {
    metricId: "revenue.pending_bookings",
    uiLabel: "Pending bookings",
    pageSection: "revenue_and_receivables",
    testId: "office-metric-revenue-pending-bookings",
    valueKind: "zar_rand",
    uiFormattingRule: "segment value is ZAR number",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "paymentsSnapshot.pendingZar",
      helper: "dashboard-stats pendingPaymentsRes aggregation",
      notes: "limit 1000",
    },
    databaseSource: {
      table: "bookings",
      columns: ["status", "payment_status", "amount_paid_cents", "total_paid_zar", "total_price"],
      filters: "status=pending_payment AND payment_status in (pending,pending_payment)",
      joins: "none",
      notes: "Amount fallback: amount_paid_cents → total_paid_zar → total_price",
    },
    authoritativeCalculationId: "db.revenue.pending_zar",
    timezone: "n/a",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Quoted/paid-cent totals for pending_payment bookings awaiting payment.",
  },
  {
    metricId: "revenue.overdue_invoices",
    uiLabel: "Overdue invoices",
    pageSection: "revenue_and_receivables",
    testId: "office-metric-revenue-overdue-invoices",
    valueKind: "zar_rand",
    uiFormattingRule: "segment value is ZAR number",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "paymentsSnapshot.overdueZar",
      helper: "dashboard-stats overdueMonthlyInvoicesRes",
      notes: "limit 1000; sum positive balance_cents",
    },
    databaseSource: {
      table: "monthly_invoices",
      columns: ["balance_cents", "status", "is_overdue"],
      filters: "status='overdue' OR is_overdue=true",
      joins: "none",
      notes: "balance_cents is generated (total_amount_cents - amount_paid_cents)",
    },
    authoritativeCalculationId: "db.revenue.overdue_zar",
    timezone: "n/a",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Sum of positive balance_cents on overdue monthly invoices.",
  },
  {
    metricId: "summary.bookings_30d",
    uiLabel: "Bookings (30d)",
    pageSection: "summary_cards",
    testId: "office-metric-summary-bookings-30d",
    valueKind: "integer",
    uiFormattingRule: "integer string",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "totalBookingsWindow",
      helper: "computeAdminDashboardRevenueSummary.totalPaidBookingsWindow",
      notes: "Paid revenue-eligible in last 30d by payment_completed_at",
    },
    databaseSource: {
      table: "bookings",
      columns: ["payment_completed_at", "payment_status"],
      filters: "eligible AND payment_completed_at >= now-30d",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.window_count",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Count of revenue-eligible bookings paid in the trailing 30-day window.",
  },
  {
    metricId: "summary.avg_booking_value",
    uiLabel: "Avg booking value",
    pageSection: "summary_cards",
    testId: "office-metric-summary-avg-booking-value",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA}",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "avgBookingValueZar",
      helper: "computeAdminDashboardRevenueSummary",
      notes: "round(windowRevenueZar / totalPaidBookingsWindow)",
    },
    databaseSource: {
      table: "bookings",
      columns: ["payment_completed_at", "amount_paid_cents", "total_paid_zar"],
      filters: "eligible in 30d window",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.avg_booking_value_zar",
    timezone: "Africa/Johannesburg",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Integer average ZAR of revenue-eligible payments in the 30-day window.",
  },
  {
    metricId: "summary.pending_payments",
    uiLabel: "Pending payments",
    pageSection: "summary_cards",
    testId: "office-metric-summary-pending-payments",
    valueKind: "zar_rand",
    uiFormattingRule: "R {rounded integer en-ZA}",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "paymentsSnapshot.pendingZar",
      helper: "dashboard-stats",
      notes: "",
    },
    databaseSource: {
      table: "bookings",
      columns: ["status", "payment_status", "amount_paid_cents", "total_paid_zar", "total_price"],
      filters: "pending_payment",
      joins: "none",
      notes: "",
    },
    authoritativeCalculationId: "db.revenue.pending_zar",
    timezone: "n/a",
    comparisonRule: "exact",
    tolerance: 0,
    required: true,
    businessRuleExplanation: "Same pending ZAR as Revenue & receivables pending bookings.",
  },
  {
    metricId: "summary.system_health",
    uiLabel: "System health",
    pageSection: "summary_cards",
    testId: "office-metric-summary-system-health",
    valueKind: "string",
    uiFormattingRule: "Healthy | {n} errors | Attention",
    applicationSource: {
      endpoint: "/api/admin/dashboard-stats",
      responsePath: "systemStatus.{website,bookingEngine,paymentGateway,cronErrorsLast24h}",
      helper: "buildDashboardSystemStatusFromOfficeOps / collectOfficeOpsHealthSignals",
      notes: "Composite of logs, cron_runs, failed_jobs, production health scan",
    },
    databaseSource: {
      table: "system_logs, cron_runs, failed_jobs, cleaners (+ production health scan)",
      columns: ["level", "created_at", "status", "job_name"],
      filters: "multi-signal; not a single SQL metric",
      joins: "multi",
      notes: "Independent DB layer cannot fully reproduce production health scan without same scanner",
    },
    authoritativeCalculationId: "db.system_health.label",
    timezone: "mixed",
    comparisonRule: "normalized_string",
    tolerance: 0,
    required: true,
    businessRuleExplanation:
      "Healthy only when website, bookingEngine, and paymentGateway are all operational; else cron error count or Attention.",
  },
];

export function getOfficeMetricRegistry(): MetricRegistryEntry[] {
  return OFFICE_METRIC_REGISTRY;
}

export function getRequiredOfficeMetrics(): MetricRegistryEntry[] {
  return OFFICE_METRIC_REGISTRY.filter((m) => m.required);
}
