import type { OfficeOpsServiceCard, OfficeOpsServiceId, OfficeOpsServiceStatus } from "@/lib/admin/officeOpsHealth";
import type {
  ProductionHealthFinding,
  ProductionHealthSeverity,
  ProductionHealthSummary,
} from "@/lib/observability/productionHealthMetrics";

export type UnifiedOpsHealthStatus = "healthy" | "degraded" | "down" | "critical";

export type UnifiedIssueBreakdown = {
  critical: number;
  high: number;
  medium: number;
  low: number;
  info: number;
};

const CRITICAL_SERVICE_IDS = new Set<OfficeOpsServiceId>([
  "website",
  "booking_engine",
  "payment_gateway",
  "database",
]);

const SERVICE_STATUS_SEVERITY: Record<OfficeOpsServiceStatus, ProductionHealthSeverity | null> = {
  operational: null,
  maintenance: "info",
  degraded: "medium",
  down: "critical",
};

function serviceFindingCode(serviceId: OfficeOpsServiceId, scope: "current" | "period", status: OfficeOpsServiceStatus): string {
  return `service_${serviceId}_${status}_${scope}`;
}

function severityForServiceIssue(
  service: OfficeOpsServiceCard,
  scope: "current" | "period",
  status: OfficeOpsServiceStatus,
): ProductionHealthSeverity {
  if (status === "down") {
    if (service.id === "notifications") return "high";
    return scope === "current" ? "critical" : "high";
  }
  if (status === "degraded") {
    if (service.id === "notifications") return "high";
    if (service.id === "database") return "medium";
    if (service.id === "website") return "medium";
    return "medium";
  }
  return "info";
}

function messageForServiceIssue(
  service: OfficeOpsServiceCard,
  scope: "current" | "period",
  status: OfficeOpsServiceStatus,
): string {
  const detail = scope === "current" ? service.currentDetail : service.periodDetail;
  const timeframe = scope === "current" ? "currently" : "over the last 30 days";
  if (status === "down") {
    return `${service.name} is unavailable ${timeframe}. ${detail ?? "Probe or delivery checks failed."}`;
  }
  if (status === "degraded") {
    return `${service.name} is degraded ${timeframe}. ${detail ?? "Elevated errors or latency detected."}`;
  }
  return `${service.name} is in maintenance ${timeframe}. ${detail ?? "Service temporarily limited."}`;
}

/** Generates scanner findings from live service card signals. */
export function deriveServiceHealthFindings(services: readonly OfficeOpsServiceCard[]): ProductionHealthFinding[] {
  const findings: ProductionHealthFinding[] = [];

  for (const service of services) {
    for (const scope of ["current", "period"] as const) {
      const status = scope === "current" ? service.currentStatus : service.periodStatus;
      if (status === "operational") continue;
      if (scope === "period" && service.currentStatus !== "operational") continue;

      const severity = severityForServiceIssue(service, scope, status);
      findings.push({
        code: serviceFindingCode(service.id, scope, status) as ProductionHealthFinding["code"],
        severity,
        count: 1,
        message: messageForServiceIssue(service, scope, status),
        sampleIds: [service.id],
        diagnostics: {
          source: "service_card",
          serviceId: service.id,
          serviceName: service.name,
          scope,
          status,
          category: service.name,
          lastFailure: detailForService(service),
          autoGenerated: true,
        },
      });
    }
  }

  return findings;
}

function detailForService(service: OfficeOpsServiceCard): string | null {
  if (service.currentStatus !== "operational") return service.currentDetail;
  return service.periodDetail;
}

function sumFindingTotals(findings: readonly ProductionHealthFinding[]): UnifiedIssueBreakdown {
  const totals: UnifiedIssueBreakdown = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const finding of findings) {
    totals[finding.severity] += finding.count;
  }
  return totals;
}

/** Merges production scan findings with service-derived findings into one summary. */
export function mergeUnifiedHealthFindings(params: {
  scanSummary: ProductionHealthSummary | null;
  serviceFindings: readonly ProductionHealthFinding[];
  fetchedAt: string;
  scanLimit: number;
  scanDegraded?: boolean;
  scanError?: string;
}): ProductionHealthSummary {
  const scanFindings = params.scanSummary?.findings ?? [];
  const mergedFindings = [...scanFindings, ...params.serviceFindings];
  const totals = sumFindingTotals(mergedFindings);

  return {
    ok: true,
    generatedAt: params.scanSummary?.generatedAt ?? params.fetchedAt,
    scanLimit: params.scanSummary?.scanLimit ?? params.scanLimit,
    findings: mergedFindings,
    totals,
    degraded: params.scanDegraded === true || params.scanSummary?.degraded === true || Boolean(params.scanError),
  };
}

export function evaluateUnifiedPlatformStatus(
  services: readonly OfficeOpsServiceCard[],
  mergedSummary: ProductionHealthSummary,
): UnifiedOpsHealthStatus {
  const anyCriticalServiceDown = services.some(
    (service) =>
      CRITICAL_SERVICE_IDS.has(service.id) &&
      (service.currentStatus === "down" || service.periodStatus === "down"),
  );
  const anyServiceDown = services.some(
    (service) => service.currentStatus === "down" || service.periodStatus === "down",
  );
  const anyServiceDegraded = services.some(
    (service) => service.currentStatus === "degraded" || service.periodStatus === "degraded",
  );
  const anyServiceMaintenance = services.some(
    (service) => service.currentStatus === "maintenance" || service.periodStatus === "maintenance",
  );

  if (mergedSummary.totals.critical > 0 || anyCriticalServiceDown) return "critical";
  if (anyServiceDown) return "down";
  if (
    mergedSummary.degraded === true ||
    mergedSummary.totals.high > 0 ||
    mergedSummary.totals.medium > 0 ||
    anyServiceDegraded
  ) {
    return "degraded";
  }
  if (mergedSummary.totals.low > 0 || mergedSummary.totals.info > 0 || anyServiceMaintenance) {
    return "degraded";
  }
  return "healthy";
}

export function mapUnifiedStatusToProductionHealthStatus(
  status: UnifiedOpsHealthStatus,
): "healthy" | "degraded" | "critical" {
  if (status === "critical" || status === "down") return status === "critical" ? "critical" : "degraded";
  if (status === "degraded") return "degraded";
  return "healthy";
}

export function unifiedStatusDescription(status: UnifiedOpsHealthStatus): string {
  if (status === "healthy") return "No production health findings in the bounded scan.";
  if (status === "degraded") return "Active production issues detected.";
  if (status === "down") return "Critical production outage detected.";
  return "Critical drift exists and should be triaged before routine operational changes.";
}

export function validateHealthConsistency(params: {
  services: readonly OfficeOpsServiceCard[];
  issuesNow: number;
  mergedSummary: ProductionHealthSummary;
  unifiedStatus: UnifiedOpsHealthStatus;
}): boolean {
  const activeServiceIssues = params.services.filter(
    (service) => service.currentStatus !== "operational" || service.periodStatus !== "operational",
  ).length;
  const totalFindings = params.mergedSummary.findings.reduce((sum, finding) => sum + finding.count, 0);

  if (params.unifiedStatus === "healthy") {
    if (params.issuesNow > 0 || activeServiceIssues > 0 || totalFindings > 0) return false;
    return true;
  }

  if (params.issuesNow > 0 && totalFindings === 0) return false;
  if (activeServiceIssues > 0 && totalFindings === 0) return false;
  return true;
}

export function countActiveServiceIssues(services: readonly OfficeOpsServiceCard[]): number {
  return services.filter((service) => service.currentStatus !== "operational").length;
}

export function isServiceFinding(finding: ProductionHealthFinding): boolean {
  return finding.diagnostics?.source === "service_card" || String(finding.code).startsWith("service_");
}

export { SERVICE_STATUS_SEVERITY };
