/** Supabase `select` fragment for customer dashboard booking lists (keep in sync with {@link BookingRow}). */
export const CUSTOMER_BOOKING_SELECT = [
  "id",
  /** Ownership columns for customer API access checks (same viewer as auth session). */
  "user_id",
  "customer_email",
  "service",
  "date",
  "time",
  "location",
  "total_paid_zar",
  "total_price",
  "price_breakdown",
  "pricing_version_id",
  "amount_paid_cents",
  "currency",
  "status",
  "dispatch_status",
  "assignment_type",
  "fallback_reason",
  "payment_needs_follow_up",
  "selected_cleaner_id",
  "payment_status",
  "booking_snapshot",
  "created_at",
  "paystack_reference",
  "cleaner_id",
  /*
   * H-8 — exposes the team-lead cleaner UUID to the customer dashboard so
   * the "Reviewable bookings" filter can fall back to it when team jobs
   * have `cleaner_id=null`. Read-only on the client; payout ownership
   * itself is owned by the dispatch / completion paths.
   */
  "payout_owner_cleaner_id",
  "cleaner_response_status",
  "assigned_at",
  "accepted_at",
  "en_route_at",
  "started_at",
  "completed_at",
  "payment_completed_at",
  "is_recurring_generated",
  "billing_type",
  "is_team_job",
  "team_id",
  "payout_status",
  "payout_paid_at",
  "admin_recurring_unpaid_completion_override_at",
  "admin_recurring_unpaid_completion_override_by",
  "duration_minutes",
  "rooms",
  "bathrooms",
  "extras",
  "monthly_invoice_id",
  "is_monthly_billing_booking",
  "monthly_invoices(status,is_closed)",
  "cleaners(full_name,phone)",
].join(",");
