/**
 * Single source of truth for `public.user_events.event_type` values (Postgres check constraint).
 * Keep in sync with latest `user_events_event_type_check` migration.
 */
export const USER_EVENT_TYPES_DB = [
  "booking_created",
  "booking_completed",
  "slot_selected",
  "extra_added",
  "recommendation_clicked",
  "flow_step_viewed",
  "flow_drop_off",
  "booking_agent_quote",
  "booking_agent_confirm",
  "page_view",
  "start_booking",
  "view_price",
  "select_time",
  "complete_booking",
  "referral_created",
  "referral_completed",
  "referral_rewarded",
  "checkout_discount_applied",
  "cleaner_checkout_attribution",
  "growth_retention_reminder",
  "growth_win_back",
  "growth_ltv_message",
  "cleaners_loaded",
  "times_loaded",
  "price_calculated",
  "booking_started",
  "booking_upsell_interaction",
  "homepage_continue_booking",
  "homepage_cta_click",
  "homepage_service_select",
  "pricing_loaded",
  "homepage_abandon",
  "homepage_scroll",
  "price_updated",
  "booking_step_details_started",
  "booking_service_selected",
  "booking_addon_selected",
  "booking_continue_schedule",
  "booking_date_selected",
  "booking_time_selected",
  "booking_cleaner_selected",
  "booking_cta_clicked",
  "booking_validation_failed",
  "booking_schedule_fetch_failed",
  "booking_payment_started",
  "booking_paystack_opened",
  "booking_recovery_prompt_shown",
  "booking_recovery_saved",
  "booking_recovery_whatsapp_clicked",
  "review_submitted",
  "review_prompt_sent",
  "review_prompt_clicked",
  "payment_initiated",
  "payment_completed",
  "blog_scroll",
  "blog_cta_click",
  "blog_time_on_page",
  "blog_toc_click",
  "blog_toc_section_engagement",
  "seo_location_scroll",
  "seo_cta_click",
  "seo_service_card_click",
  "seo_faq_expand",
  "seo_pricing_interaction",
] as const;

export type UserEventTypeDb = (typeof USER_EVENT_TYPES_DB)[number];

export const USER_EVENT_TYPES_ALLOWED_SET: ReadonlySet<string> = new Set(USER_EVENT_TYPES_DB);

/**
 * Client + dashboard canonical names (`event_type` strings). Prefer these constants over literals
 * everywhere so taxonomy stays drift-free.
 */
export const ANALYTICS_EVENTS = {
  PAGE_VIEW: "page_view",
  START_BOOKING: "start_booking",
  VIEW_PRICE: "view_price",
  SELECT_TIME: "select_time",
  COMPLETE_BOOKING: "complete_booking",
  CLEANERS_LOADED: "cleaners_loaded",
  TIMES_LOADED: "times_loaded",
  PRICE_CALCULATED: "price_calculated",
  BOOKING_STARTED: "booking_started",
  BOOKING_UPSELL_INTERACTION: "booking_upsell_interaction",
  HOMEPAGE_CONTINUE_BOOKING: "homepage_continue_booking",
  HOMEPAGE_CTA_CLICK: "homepage_cta_click",
  HOMEPAGE_SERVICE_SELECT: "homepage_service_select",
  PRICING_LOADED: "pricing_loaded",
  HOMEPAGE_ABANDON: "homepage_abandon",
  HOMEPAGE_SCROLL: "homepage_scroll",
  PRICE_UPDATED: "price_updated",
  BOOKING_STEP_DETAILS_STARTED: "booking_step_details_started",
  BOOKING_SERVICE_SELECTED: "booking_service_selected",
  BOOKING_ADDON_SELECTED: "booking_addon_selected",
  BOOKING_CONTINUE_SCHEDULE: "booking_continue_schedule",
  BOOKING_DATE_SELECTED: "booking_date_selected",
  BOOKING_TIME_SELECTED: "booking_time_selected",
  BOOKING_CLEANER_SELECTED: "booking_cleaner_selected",
  BOOKING_CTA_CLICKED: "booking_cta_clicked",
  BOOKING_VALIDATION_FAILED: "booking_validation_failed",
  BOOKING_SCHEDULE_FETCH_FAILED: "booking_schedule_fetch_failed",
  BOOKING_PAYMENT_STARTED: "booking_payment_started",
  BOOKING_PAYSTACK_OPENED: "booking_paystack_opened",
  BOOKING_RECOVERY_PROMPT_SHOWN: "booking_recovery_prompt_shown",
  BOOKING_RECOVERY_SAVED: "booking_recovery_saved",
  BOOKING_RECOVERY_WHATSAPP_CLICKED: "booking_recovery_whatsapp_clicked",
  REVIEW_PROMPT_CLICKED: "review_prompt_clicked",
  PAYMENT_INITIATED: "payment_initiated",
  PAYMENT_COMPLETED: "payment_completed",
  BLOG_SCROLL: "blog_scroll",
  BLOG_CTA_CLICK: "blog_cta_click",
  BLOG_TIME_ON_PAGE: "blog_time_on_page",
  BLOG_TOC_CLICK: "blog_toc_click",
  BLOG_TOC_SECTION_ENGAGEMENT: "blog_toc_section_engagement",
  SEO_LOCATION_SCROLL: "seo_location_scroll",
  SEO_CTA_CLICK: "seo_cta_click",
  SEO_SERVICE_CARD_CLICK: "seo_service_card_click",
  SEO_FAQ_EXPAND: "seo_faq_expand",
  SEO_PRICING_INTERACTION: "seo_pricing_interaction",
  BOOKING_COMPLETED: "booking_completed",
  /** Assistant / legacy slot signal (still valid in DB). */
  SLOT_SELECTED: "slot_selected",
  EXTRA_ADDED: "extra_added",
  RECOMMENDATION_CLICKED: "recommendation_clicked",
} as const satisfies Record<string, UserEventTypeDb>;

export type AnalyticsClientEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
