"use client";

import { useMemo, useState } from "react";
import { adminFetch, useAdminData } from "@/hooks/useAdminData";

type LinkRow={id:string;source_url:string;source_domain:string;target_url:string|null;first_seen_at:string;last_seen_at:string;verification_status:string;verified_at:string|null;suspicious:boolean;suspicious_reason:string|null;review_status:string;notes:string|null};
type DomainRow={domain:string;links:number;lastSeen:string;suspicious:number};
type Opportunity={id:string;domain:string;url:string|null;opportunity_type:string;priority:string;status:string;rationale:string|null;owner:string|null;created_at:string;updated_at:string};
type ImportRow={id:string;source:string;import_type:string;imported_at:string;row_count:number;new_links:number;notes:string|null};
type Payload={summary:{backlinks:number;referringDomains:number;newSinceLastImport:number;verifiedPresent:number;lost:number;suspicious:number;openOpportunities:number};links:LinkRow[];domains:DomainRow[];imports:ImportRow[];opportunities:Opportunity[]};

export function BacklinkManagementDashboard(){
 const {data,loading,error,refetch}=useAdminData<Payload>("/api/admin/seo-insights/backlinks");
 const [csv,setCsv]=useState(""); const [importType,setImportType]=useState("sample"); const [busy,setBusy]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null);
 const [domain,setDomain]=useState(""); const [rationale,setRationale]=useState("");
 const suspicious=useMemo(()=>data?.links.filter(l=>l.suspicious&&l.review_status==="unreviewed")??[],[data]);
 async function act(payload:Record<string,unknown>,key:string){setBusy(key);setActionError(null);try{const r=await adminFetch("/api/admin/seo-insights/backlinks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(r.error||"Action failed");await refetch();return r;}catch(e){setActionError(e instanceof Error?e.message:"Action failed");}finally{setBusy(null);}}
 async function importCsv(){const r=await act({action:"import_csv",csv,importType},"import");if(r?.ok)setCsv("");}
 async function addOpportunity(){const r=await act({action:"add_opportunity",domain,rationale},"opp");if(r?.ok){setDomain("");setRationale("");}}
 if(loading)return <div className="rounded-2xl border bg-white p-6 text-sm text-slate-500">Loading backlink management…</div>;
 if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
 if(!data)return null;
 const cards=[['Backlinks',data.summary.backlinks],['Referring domains',data.summary.referringDomains],['New since import',data.summary.newSinceLastImport],['Verified present',data.summary.verifiedPresent],['Confirmed lost',data.summary.lost],['Needs review',data.summary.suspicious],['Open opportunities',data.summary.openOpportunities]] as const;
 return <div className="space-y-6">
  <div><h1 className="text-2xl font-bold text-slate-950">Backlink management</h1><p className="mt-1 text-sm text-slate-600">Free-first backlink tracking using Google Search Console Links exports, Shalean verification, and opportunity management. Referring-domain growth is a proxy, not a commercial authority score.</p></div>
  {actionError&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{actionError}</div>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([k,v])=><div key={k} className="rounded-2xl border bg-white p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{k}</div><div className="mt-2 text-2xl font-bold text-slate-950">{v}</div></div>)}</div>
  <div className="grid gap-6 lg:grid-cols-2">
   <div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold text-slate-950">Import Search Console Links CSV</h2><p className="mt-1 text-xs text-slate-500">Search Console → Links → Export external links → Latest links or More sample links. Imported samples do not automatically mark missing links as lost.</p><select value={importType} onChange={e=>setImportType(e.target.value)} className="mt-4 w-full rounded-xl border px-3 py-2 text-sm"><option value="sample">More sample links</option><option value="latest">Latest links</option><option value="drilldown">Page/domain drilldown</option></select><textarea value={csv} onChange={e=>setCsv(e.target.value)} rows={9} placeholder={'Paste CSV here, for example:\nLinks\nhttps://example.com/page'} className="mt-3 w-full rounded-xl border p-3 font-mono text-xs"/><button onClick={importCsv} disabled={!csv.trim()||busy==="import"} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy==="import"?"Importing…":"Import backlinks"}</button></div>
   <div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold text-slate-950">Add backlink opportunity</h2><p className="mt-1 text-xs text-slate-500">Track directories, partners, publications, local sites and outreach targets without a paid backlink platform.</p><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.co.za" className="mt-4 w-full rounded-xl border px-3 py-2 text-sm"/><textarea value={rationale} onChange={e=>setRationale(e.target.value)} rows={4} placeholder="Why this domain is relevant" className="mt-3 w-full rounded-xl border p-3 text-sm"/><button onClick={addOpportunity} disabled={!domain.trim()||busy==="opp"} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Add opportunity</button></div>
  </div>
  <div className="grid gap-6 xl:grid-cols-2">
   <div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Top referring domains</h2></div><div className="max-h-[420px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Domain</th><th className="p-3">Links</th><th className="p-3">Review flags</th></tr></thead><tbody>{data.domains.slice(0,100).map(d=><tr key={d.domain} className="border-t"><td className="p-3 font-medium">{d.domain}</td><td className="p-3">{d.links}</td><td className="p-3">{d.suspicious||'—'}</td></tr>)}</tbody></table></div></div>
   <div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Suspicious-link review</h2><p className="text-xs text-slate-500">Flags are review prompts only. Shalean does not auto-disavow links.</p></div><div className="max-h-[420px] overflow-auto divide-y">{suspicious.length?suspicious.map(l=><div key={l.id} className="p-4"><a href={l.source_url} target="_blank" rel="noreferrer" className="break-all text-sm font-medium hover:underline">{l.source_url}</a><p className="mt-1 text-xs text-amber-700">{l.suspicious_reason}</p><div className="mt-3 flex gap-2"><button onClick={()=>act({action:"review",id:l.id,status:"safe"},`safe-${l.id}`)} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Mark safe</button><button onClick={()=>act({action:"review",id:l.id,status:"watch"},`watch-${l.id}`)} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Watch</button><button onClick={()=>act({action:"review",id:l.id,status:"disavow_review"},`disavow-${l.id}`)} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Disavow review</button></div></div>):<div className="p-6 text-sm text-slate-500">No unreviewed suspicious links.</div>}</div></div>
  </div>
  <div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Backlinks</h2><p className="text-xs text-slate-500">Use Verify to confirm whether an imported source page still contains a link to shalean.co.za.</p></div><div className="max-h-[620px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Source</th><th className="p-3">Status</th><th className="p-3">First seen</th><th className="p-3">Action</th></tr></thead><tbody>{data.links.map(l=><tr key={l.id} className="border-t align-top"><td className="p-3"><a href={l.source_url} target="_blank" rel="noreferrer" className="break-all font-medium hover:underline">{l.source_domain}</a><div className="mt-1 max-w-xl break-all text-xs text-slate-500">{l.source_url}</div></td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{l.verification_status}</span></td><td className="p-3 text-xs text-slate-500">{new Date(l.first_seen_at).toLocaleDateString()}</td><td className="p-3"><button onClick={()=>act({action:"verify",id:l.id},`verify-${l.id}`)} disabled={busy===`verify-${l.id}`} className="rounded-lg border px-3 py-1.5 text-xs font-semibold disabled:opacity-50">{busy===`verify-${l.id}`?"Verifying…":"Verify"}</button></td></tr>)}</tbody></table>{!data.links.length&&<div className="p-8 text-center text-sm text-slate-500">No backlink exports imported yet.</div>}</div></div>
  <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Opportunity pipeline</h2><div className="mt-3 space-y-2">{data.opportunities.map(o=><div key={o.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{o.domain}</div><div className="mt-1 text-xs text-slate-500">{o.rationale||o.opportunity_type}</div></div><select value={o.status} onChange={e=>act({action:"update_opportunity",id:o.id,status:e.target.value},`opp-${o.id}`)} className="rounded-lg border bg-white px-2 py-1 text-xs"><option value="open">Open</option><option value="contacted">Contacted</option><option value="won">Won</option><option value="lost">Lost</option><option value="dismissed">Dismissed</option></select></div></div>)}{!data.opportunities.length&&<p className="text-sm text-slate-500">No opportunities yet.</p>}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Import history</h2><div className="mt-3 space-y-2">{data.imports.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="font-medium">{new Date(i.imported_at).toLocaleString()} · {i.import_type}</div><div className="mt-1 text-xs text-slate-500">{i.row_count} rows · {i.new_links} first-seen links</div></div>)}{!data.imports.length&&<p className="text-sm text-slate-500">No imports yet.</p>}</div></div></div>
 </div>;
}
