"use client";

import { useState } from "react";
import { useAdminData } from "@/hooks/useAdminData";

 type Payload={summary:{total:number;indexed:number;notIndexed:number;excluded:number;blocked:number;unknown:number;regressions:number;actionRequired:number};rows:Array<{url:string;path:string;page_group:string;priority:string;state:string;coverage_state:string|null;reason:string|null;last_crawl_time:string|null;inspected_at:string|null;google_canonical:string|null;user_canonical:string|null;regression_detected:boolean;action_required:boolean}>;runs:Array<{id:string;started_at:string;status:string;inspected:number;indexed:number;not_indexed:number;excluded:number;blocked:number;regressions:number;errors:number}>};

export function IndexingManagementDashboard(){
 const {data,loading,error,refetch}=useAdminData<Payload>("/api/admin/seo-insights/indexing");
 const [running,setRunning]=useState(false); const [runError,setRunError]=useState<string|null>(null);
 async function run(){setRunning(true);setRunError(null);try{const r=await fetch("/api/admin/seo-insights/indexing",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Inspection failed");await refetch();}catch(e){setRunError(e instanceof Error?e.message:"Inspection failed");}finally{setRunning(false);}}
 if(loading)return <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading indexing coverage…</div>;
 if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
 if(!data)return null;
 const cards:[[string,number],...[string,number][]]=[["Sitemap URLs",data.summary.total],["Indexed",data.summary.indexed],["Not indexed",data.summary.notIndexed],["Excluded",data.summary.excluded],["Blocked",data.summary.blocked],["Regressions",data.summary.regressions],["Needs action",data.summary.actionRequired]];
 return <div className="space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Indexing management</h1><p className="mt-1 text-sm text-slate-500">Canonical sitemap URLs compared with Google Search Console URL Inspection.</p></div><button onClick={run} disabled={running} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{running?"Inspecting…":"Run inspection now"}</button></div>
  {runError?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{runError}</div>:null}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>)}</div>
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Sitemap vs Google index</h2><p className="text-xs text-slate-500">Priority pages and regressions are shown first.</p></div><div className="max-h-[680px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Page</th><th className="px-4 py-3">Group</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3">Last crawl</th></tr></thead><tbody className="divide-y divide-slate-100">{data.rows.map(row=><tr key={row.url} className={row.action_required?"bg-amber-50/50":""}><td className="px-4 py-3"><a className="font-medium text-slate-900 hover:underline" href={row.url} target="_blank" rel="noreferrer">{row.path}</a><p className="mt-1 text-xs text-slate-500">{row.priority.toUpperCase()}{row.regression_detected?" · REGRESSION":""}</p></td><td className="px-4 py-3 text-slate-600">{row.page_group}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{row.state.replace("_"," ")}</span></td><td className="max-w-[360px] px-4 py-3 text-slate-600">{row.reason||row.coverage_state||"—"}</td><td className="px-4 py-3 text-slate-500">{row.last_crawl_time?new Date(row.last_crawl_time).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Inspection history</h2><div className="mt-3 space-y-2">{data.runs.map(run=><div key={run.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{new Date(run.started_at).toLocaleString()} · {run.status}</span><span className="text-slate-500">{run.inspected} inspected · {run.indexed} indexed · {run.regressions} regressions · {run.errors} errors</span></div>)}</div></div>
 </div>;
}
