"use client";

import { useAdminData } from "@/hooks/useAdminData";

type LandingRow = { path:string; sessions:number; booking_starts:number; completed_bookings:number; session_to_booking_pct:number; start_to_booking_pct:number; revenue_zar:number; revenue_per_session_zar:number; target_keywords:string[]; gsc_clicks:number; gsc_impressions:number; gsc_position:number|null };
type ClusterRow = { path:string; keywords:string[]; sessions:number; booking_starts:number; completed_bookings:number; conversion_pct:number; revenue_zar:number; gsc_clicks:number; gsc_impressions:number; gsc_position:number|null };
type Payload = { since:string; attribution_note:string; summary:{ organic_sessions:number; organic_booking_starts:number; organic_completed_bookings:number; organic_conversion_pct:number; organic_revenue_zar:number; revenue_per_organic_session_zar:number; unattributed_sessions:number; revenue_linked_bookings:number }; byLanding:LandingRow[]; keywordClusters:ClusterRow[] };

const zar = (v:number) => new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(v);

export function OrganicRevenueDashboard(){
  const {data,loading,error}=useAdminData<Payload>("/api/admin/seo-insights/organic-revenue");
  if(loading&&!data) return <div className="rounded-2xl border bg-white p-6">Loading organic conversion and revenue…</div>;
  const s=data?.summary;
  return <div className="space-y-6">
    <div><h1 className="text-2xl font-bold text-slate-950">Organic Conversion & Revenue</h1><p className="mt-1 text-sm text-slate-600">Connect SEO landing pages to booking starts, completed bookings and attributable revenue.</p></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {data?.attribution_note&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900"><strong>Attribution rule:</strong> {data.attribution_note}</div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {[["Organic sessions",s?.organic_sessions??0],["Booking starts",s?.organic_booking_starts??0],["Completed bookings",s?.organic_completed_bookings??0],["Conversion",`${s?.organic_conversion_pct??0}%`],["Organic revenue",zar(s?.organic_revenue_zar??0)],["Revenue / session",zar(s?.revenue_per_organic_session_zar??0)],["Revenue-linked bookings",s?.revenue_linked_bookings??0],["Unattributed sessions",s?.unattributed_sessions??0]].map(([k,v])=><div key={String(k)} className="rounded-2xl border bg-white p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{k}</div><div className="mt-2 text-2xl font-bold text-slate-950">{v}</div></div>)}
    </div>
    <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-bold text-slate-950">Landing-page revenue</h2><p className="mt-1 text-sm text-slate-500">Explicitly attributed organic sessions only.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Landing page</th><th className="p-3">Sessions</th><th className="p-3">Starts</th><th className="p-3">Bookings</th><th className="p-3">Conv.</th><th className="p-3">Revenue</th><th className="p-3">GSC</th><th className="p-3">Target keywords</th></tr></thead><tbody>{(data?.byLanding??[]).map(r=><tr key={r.path} className="border-t align-top"><td className="p-3 font-semibold text-slate-900">{r.path}</td><td className="p-3">{r.sessions}</td><td className="p-3">{r.booking_starts}</td><td className="p-3">{r.completed_bookings}</td><td className="p-3">{r.session_to_booking_pct}%</td><td className="p-3 font-semibold">{zar(r.revenue_zar)}</td><td className="p-3">{r.gsc_clicks} clicks<br/><span className="text-xs text-slate-500">{r.gsc_impressions} impr. · {r.gsc_position==null?"—":`#${r.gsc_position.toFixed(1)}`}</span></td><td className="p-3 text-xs text-slate-600">{r.target_keywords.length?r.target_keywords.join(", "):"No keyword owner"}</td></tr>)}</tbody></table>{!(data?.byLanding?.length)&&<div className="p-8 text-center text-sm text-slate-500">No explicitly attributed organic sessions found in this 90-day window yet.</div>}</div></section>
    <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-bold text-slate-950">Keyword-cluster business value</h2><p className="mt-1 text-sm text-slate-500">Keyword portfolio targets grouped by their canonical landing page.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Cluster / target</th><th className="p-3">Keywords</th><th className="p-3">GSC visibility</th><th className="p-3">Sessions</th><th className="p-3">Bookings</th><th className="p-3">Revenue</th></tr></thead><tbody>{(data?.keywordClusters??[]).map(r=><tr key={r.path} className="border-t align-top"><td className="p-3 font-semibold">{r.path}</td><td className="p-3 text-xs text-slate-600">{r.keywords.join(", ")}</td><td className="p-3">{r.gsc_clicks} clicks · {r.gsc_impressions} impr.<div className="text-xs text-slate-500">Avg position {r.gsc_position==null?"—":r.gsc_position.toFixed(1)}</div></td><td className="p-3">{r.sessions}</td><td className="p-3">{r.completed_bookings} <span className="text-xs text-slate-500">({r.conversion_pct}%)</span></td><td className="p-3 font-semibold">{zar(r.revenue_zar)}</td></tr>)}</tbody></table>{!(data?.keywordClusters?.length)&&<div className="p-8 text-center text-sm text-slate-500">Add active keywords with target pages in Keyword Portfolio to create business-value clusters.</div>}</div></section>
  </div>;
}
