import {
  CUSTOMER_SUPPORT_EMAIL,
  CUSTOMER_SUPPORT_TELEPHONE_DISPLAY,
  CUSTOMER_SUPPORT_TELEPHONE_E164,
  CUSTOMER_SUPPORT_TELEPHONE_TEL,
  CUSTOMER_SUPPORT_WHATSAPP_DISPLAY,
  CUSTOMER_SUPPORT_WHATSAPP_E164,
  buildCustomerSupportWhatsAppUrl,
  customerSupportWhatsAppHref,
} from "@shalean/utils/customerSupport";

export {
  CUSTOMER_SUPPORT_EMAIL,
  CUSTOMER_SUPPORT_TELEPHONE_DISPLAY,
  CUSTOMER_SUPPORT_TELEPHONE_E164,
  CUSTOMER_SUPPORT_TELEPHONE_TEL,
  CUSTOMER_SUPPORT_WHATSAPP_DISPLAY,
  CUSTOMER_SUPPORT_WHATSAPP_E164,
  buildCustomerSupportWhatsAppUrl,
  customerSupportWhatsAppHref,
};

export const CUSTOMER_SUPPORT_WHATSAPP_URL = buildCustomerSupportWhatsAppUrl();
