/** Common Cape Town suburbs for quick pick — free-text still allowed + resolve-location. */
export const SUBURB_OPTIONS = [
  "Sea Point",
  "Green Point",
  "Cape Town City Centre",
  "Gardens",
  "Tamboerskloof",
  "Oranjezicht",
  "Vredehoek",
  "Woodstock",
  "Observatory",
  "Mowbray",
  "Rondebosch",
  "Claremont",
  "Newlands",
  "Kenilworth",
  "Wynberg",
  "Constantia",
  "Bishopscourt",
  "Camps Bay",
  "Clifton",
  "Bantry Bay",
  "Fresnaye",
  "Mouille Point",
  "Three Anchor Bay",
  "Pinelands",
  "Plumstead",
  "Diep River",
  "Bergvliet",
  "Tokai",
  "Hout Bay",
  "Llandudno",
  "Milnerton",
  "Table View",
  "Bloubergstrand",
  "Parklands",
  "Century City",
  "Bellville",
  "Durbanville",
  "Parow",
  "Goodwood",
  "Somerset West",
  "Stellenbosch",
  "Strand",
  "Gordon's Bay",
  "Fish Hoek",
  "Simon's Town",
  "Muizenberg",
  "Kalk Bay",
  "Kommetjie",
  "Noordhoek",
  "Sun Valley",
] as const;

export function filterSuburbOptions(query: string, limit = 12): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...SUBURB_OPTIONS].slice(0, limit);
  return SUBURB_OPTIONS.filter((s) => s.toLowerCase().includes(q)).slice(0, limit);
}
