/**
 * Stable payment error categories for logs + API clients.
 * Safe to expose to the client (no secrets).
 */
export const PAYMENT_ERROR_CODES = {
  PAYMENT_ALREADY_COMPLETED: "PAYMENT_ALREADY_COMPLETED",
  PAYMENT_INITIALIZATION_FAILED: "PAYMENT_INITIALIZATION_FAILED",
  PAYMENT_LINK_MISSING: "PAYMENT_LINK_MISSING",
  PAYMENT_LINK_EXPIRED: "PAYMENT_LINK_EXPIRED",
  PAYMENT_ATTEMPT_ABANDONED: "PAYMENT_ATTEMPT_ABANDONED",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_REFERENCE_CONFLICT: "PAYMENT_REFERENCE_CONFLICT",
  PAYMENT_CONFIGURATION_ERROR: "PAYMENT_CONFIGURATION_ERROR",
  PAYMENT_ACCESS_DENIED: "PAYMENT_ACCESS_DENIED",
  PAYMENT_BOOKING_NOT_FOUND: "PAYMENT_BOOKING_NOT_FOUND",
  PAYMENT_NOT_PAYABLE: "PAYMENT_NOT_PAYABLE",
  PAYMENT_IN_PROGRESS: "PAYMENT_IN_PROGRESS",
} as const;

export type PaymentErrorCode = (typeof PAYMENT_ERROR_CODES)[keyof typeof PAYMENT_ERROR_CODES];
