-- ============================================================================
-- Shalean — locations reference (Western Cape service areas)
-- ============================================================================
-- Prerequisites: public.locations exists (20260432+). For NOT NULL slug + RLS use 20260435 first.
--
-- Cleaning rules applied to source labels:
--   • Remove leading "House Cleaning" (case-insensitive)
--   • Trim; display names in title case (Bo-Kaap, Sea Point, V&A Waterfront, Gordon's Bay)
--   • Slugs: kebab-case, ASCII (va-waterfront, sea-point, gordons-bay)
--
-- Re-run safe: ON CONFLICT (slug) DO UPDATE syncs name/city/province.
-- Rows: 172
-- ============================================================================

insert into public.locations (name, slug, city, province)
values
  ('Airport Industria', 'airport-industria', 'Cape Town', 'Western Cape'),
  ('Amanda Glen', 'amanda-glen', 'Cape Town', 'Western Cape'),
  ('Amandelrug', 'amandelrug', 'Cape Town', 'Western Cape'),
  ('Athlone', 'athlone', 'Cape Town', 'Western Cape'),
  ('Atlantis', 'atlantis', 'Atlantis', 'Western Cape'),
  ('Avondale', 'avondale', 'Cape Town', 'Western Cape'),
  ('Banbury Estate', 'banbury-estate', 'Cape Town', 'Western Cape'),
  ('Bantry Bay', 'bantry-bay', 'Cape Town', 'Western Cape'),
  ('Beacon Hill', 'beacon-hill', 'Cape Town', 'Western Cape'),
  ('Belhar', 'belhar', 'Cape Town', 'Western Cape'),
  ('Bellville', 'bellville', 'Cape Town', 'Western Cape'),
  ('Bellville Park', 'bellville-park', 'Cape Town', 'Western Cape'),
  ('Bellville South', 'bellville-south', 'Cape Town', 'Western Cape'),
  ('Bergvliet', 'bergvliet', 'Cape Town', 'Western Cape'),
  ('Big Bay', 'big-bay', 'Cape Town', 'Western Cape'),
  ('Bishop Lavis', 'bishop-lavis', 'Cape Town', 'Western Cape'),
  ('Bishopscourt', 'bishopscourt', 'Cape Town', 'Western Cape'),
  ('Blackheath', 'blackheath', 'Cape Town', 'Western Cape'),
  ('Bloubergrant', 'bloubergrant', 'Cape Town', 'Western Cape'),
  ('Bloubergstrand', 'bloubergstrand', 'Cape Town', 'Western Cape'),
  ('Blue Downs', 'blue-downs', 'Cape Town', 'Western Cape'),
  ('Bo-Kaap', 'bo-kaap', 'Cape Town', 'Western Cape'),
  ('Bonnie Brook', 'bonnie-brook', 'Cape Town', 'Western Cape'),
  ('Boston', 'boston', 'Cape Town', 'Western Cape'),
  ('Bothasig', 'bothasig', 'Cape Town', 'Western Cape'),
  ('Brackenfell', 'brackenfell', 'Cape Town', 'Western Cape'),
  ('Brooklyn', 'brooklyn', 'Cape Town', 'Western Cape'),
  ('Burgundy Estate', 'burgundy-estate', 'Cape Town', 'Western Cape'),
  ('Camps Bay', 'camps-bay', 'Cape Town', 'Western Cape'),
  ('Cape Gate', 'cape-gate', 'Cape Town', 'Western Cape'),
  ('Cape Town', 'cape-town', 'Cape Town', 'Western Cape'),
  ('Cape Town CBD', 'cape-town-cbd', 'Cape Town', 'Western Cape'),
  ('Century City', 'century-city', 'Cape Town', 'Western Cape'),
  ('Charlotteville', 'charlotteville', 'Cape Town', 'Western Cape'),
  ('Chatsworth', 'chatsworth', 'Cape Town', 'Western Cape'),
  ('Claremont', 'claremont', 'Cape Town', 'Western Cape'),
  ('Clifton', 'clifton', 'Cape Town', 'Western Cape'),
  ('Constantia', 'constantia', 'Cape Town', 'Western Cape'),
  ('Contermanskloof', 'contermanskloof', 'Cape Town', 'Western Cape'),
  ('Croydon', 'croydon', 'Cape Town', 'Western Cape'),
  ('Daisy Park', 'daisy-park', 'Cape Town', 'Western Cape'),
  ('De Tijger', 'de-tijger', 'Cape Town', 'Western Cape'),
  ('De Waterkant', 'de-waterkant', 'Cape Town', 'Western Cape'),
  ('Diep River', 'diep-river', 'Cape Town', 'Western Cape'),
  ('Durbanville', 'durbanville', 'Cape Town', 'Western Cape'),
  ('Eerste River', 'eerste-river', 'Cape Town', 'Western Cape'),
  ('Elsies River', 'elsies-river', 'Cape Town', 'Western Cape'),
  ('Epping', 'epping', 'Cape Town', 'Western Cape'),
  ('Epping Industria', 'epping-industria', 'Cape Town', 'Western Cape'),
  ('Eversdal', 'eversdal', 'Cape Town', 'Western Cape'),
  ('Fairfield Estate', 'fairfield-estate', 'Cape Town', 'Western Cape'),
  ('Fisantekraal', 'fisantekraal', 'Cape Town', 'Western Cape'),
  ('Fish Hoek', 'fish-hoek', 'Cape Town', 'Western Cape'),
  ('Foreshore', 'foreshore', 'Cape Town', 'Western Cape'),
  ('Franschhoek', 'franschhoek', 'Franschhoek', 'Western Cape'),
  ('Fresnaye', 'fresnaye', 'Cape Town', 'Western Cape'),
  ('Gardens', 'gardens', 'Cape Town', 'Western Cape'),
  ('Gatesville', 'gatesville', 'Cape Town', 'Western Cape'),
  ('Glencairn', 'glencairn', 'Cape Town', 'Western Cape'),
  ('Goodwood', 'goodwood', 'Cape Town', 'Western Cape'),
  ('Gordon''s Bay', 'gordons-bay', 'Gordon''s Bay', 'Western Cape'),
  ('Grabouw', 'grabouw', 'Grabouw', 'Western Cape'),
  ('Green Point', 'green-point', 'Cape Town', 'Western Cape'),
  ('Groote Schuur Estate', 'groote-schuur-estate', 'Cape Town', 'Western Cape'),
  ('Gugulethu', 'gugulethu', 'Cape Town', 'Western Cape'),
  ('Hanover Park', 'hanover-park', 'Cape Town', 'Western Cape'),
  ('Harfield Village', 'harfield-village', 'Cape Town', 'Western Cape'),
  ('Heathfield', 'heathfield', 'Cape Town', 'Western Cape'),
  ('Helderberg Estate', 'helderberg-estate', 'Cape Town', 'Western Cape'),
  ('Hermanus', 'hermanus', 'Hermanus', 'Western Cape'),
  ('Highlands Estate', 'highlands-estate', 'Cape Town', 'Western Cape'),
  ('Hout Bay', 'hout-bay', 'Cape Town', 'Western Cape'),
  ('Imizamo Yethu', 'imizamo-yethu', 'Cape Town', 'Western Cape'),
  ('Kalk Bay', 'kalk-bay', 'Cape Town', 'Western Cape'),
  ('Kenilworth', 'kenilworth', 'Cape Town', 'Western Cape'),
  ('Khayelitsha', 'khayelitsha', 'Cape Town', 'Western Cape'),
  ('Kirstenhof', 'kirstenhof', 'Cape Town', 'Western Cape'),
  ('Kleinmond', 'kleinmond', 'Kleinmond', 'Western Cape'),
  ('Kraaifontein', 'kraaifontein', 'Cape Town', 'Western Cape'),
  ('Kuils River', 'kuils-river', 'Cape Town', 'Western Cape'),
  ('Lakeside', 'lakeside', 'Cape Town', 'Western Cape'),
  ('Langa', 'langa', 'Cape Town', 'Western Cape'),
  ('Loevenstein', 'loevenstein', 'Cape Town', 'Western Cape'),
  ('Maitland', 'maitland', 'Cape Town', 'Western Cape'),
  ('Maitland Garden Village', 'maitland-garden-village', 'Cape Town', 'Western Cape'),
  ('Manenberg', 'manenberg', 'Cape Town', 'Western Cape'),
  ('Marconi Beam', 'marconi-beam', 'Cape Town', 'Western Cape'),
  ('Matroosfontein', 'matroosfontein', 'Cape Town', 'Western Cape'),
  ('Meadowridge', 'meadowridge', 'Cape Town', 'Western Cape'),
  ('Melkbosstrand', 'melkbosstrand', 'Cape Town', 'Western Cape'),
  ('Milnerton', 'milnerton', 'Cape Town', 'Western Cape'),
  ('Mitchells Plain', 'mitchells-plain', 'Cape Town', 'Western Cape'),
  ('Montague Gardens', 'montague-gardens', 'Cape Town', 'Western Cape'),
  ('Monte Vista', 'monte-vista', 'Cape Town', 'Western Cape'),
  ('Mouille Point', 'mouille-point', 'Cape Town', 'Western Cape'),
  ('Muizenberg', 'muizenberg', 'Cape Town', 'Western Cape'),
  ('Ndabeni', 'ndabeni', 'Cape Town', 'Western Cape'),
  ('Newlands', 'newlands', 'Cape Town', 'Western Cape'),
  ('Newlands Forest', 'newlands-forest', 'Cape Town', 'Western Cape'),
  ('Noordhoek', 'noordhoek', 'Cape Town', 'Western Cape'),
  ('Northpine', 'northpine', 'Cape Town', 'Western Cape'),
  ('Norwood', 'norwood', 'Cape Town', 'Western Cape'),
  ('Oakdale', 'oakdale', 'Cape Town', 'Western Cape'),
  ('Oakglen', 'oakglen', 'Cape Town', 'Western Cape'),
  ('Observatory', 'observatory', 'Cape Town', 'Western Cape'),
  ('Oranjezicht', 'oranjezicht', 'Cape Town', 'Western Cape'),
  ('Ottery', 'ottery', 'Cape Town', 'Western Cape'),
  ('Paarl', 'paarl', 'Paarl', 'Western Cape'),
  ('Panorama', 'panorama', 'Cape Town', 'Western Cape'),
  ('Parklands', 'parklands', 'Cape Town', 'Western Cape'),
  ('Parow', 'parow', 'Cape Town', 'Western Cape'),
  ('Parow East', 'parow-east', 'Cape Town', 'Western Cape'),
  ('Parow North', 'parow-north', 'Cape Town', 'Western Cape'),
  ('Philippi', 'philippi', 'Cape Town', 'Western Cape'),
  ('Philippi East', 'philippi-east', 'Cape Town', 'Western Cape'),
  ('Pinelands', 'pinelands', 'Cape Town', 'Western Cape'),
  ('Plattekloof', 'plattekloof', 'Cape Town', 'Western Cape'),
  ('Plumstead', 'plumstead', 'Cape Town', 'Western Cape'),
  ('Protea Heights', 'protea-heights', 'Cape Town', 'Western Cape'),
  ('Protea Park', 'protea-park', 'Cape Town', 'Western Cape'),
  ('Retreat', 'retreat', 'Cape Town', 'Western Cape'),
  ('Richwood', 'richwood', 'Cape Town', 'Western Cape'),
  ('Rondebosch', 'rondebosch', 'Cape Town', 'Western Cape'),
  ('Rondebosch East', 'rondebosch-east', 'Cape Town', 'Western Cape'),
  ('Rosendal', 'rosendal', 'Cape Town', 'Western Cape'),
  ('Royal Ascot', 'royal-ascot', 'Cape Town', 'Western Cape'),
  ('Rylands', 'rylands', 'Cape Town', 'Western Cape'),
  ('Salt River', 'salt-river', 'Cape Town', 'Western Cape'),
  ('Sanddrift', 'sanddrift', 'Cape Town', 'Western Cape'),
  ('Scarborough', 'scarborough', 'Cape Town', 'Western Cape'),
  ('Scottsville', 'scottsville', 'Cape Town', 'Western Cape'),
  ('Sea Point', 'sea-point', 'Cape Town', 'Western Cape'),
  ('Seaforth', 'seaforth', 'Cape Town', 'Western Cape'),
  ('Sherwood', 'sherwood', 'Cape Town', 'Western Cape'),
  ('Silvertown', 'silvertown', 'Cape Town', 'Western Cape'),
  ('Simon''s Town', 'simons-town', 'Cape Town', 'Western Cape'),
  ('Somerset West', 'somerset-west', 'Somerset West', 'Western Cape'),
  ('Soneike', 'soneike', 'Cape Town', 'Western Cape'),
  ('St James', 'st-james', 'Cape Town', 'Western Cape'),
  ('Stellenbosch', 'stellenbosch', 'Stellenbosch', 'Western Cape'),
  ('Stellenridge', 'stellenridge', 'Cape Town', 'Western Cape'),
  ('Strand', 'strand', 'Strand', 'Western Cape'),
  ('Strandfontein', 'strandfontein', 'Cape Town', 'Western Cape'),
  ('Sunningdale', 'sunningdale', 'Cape Town', 'Western Cape'),
  ('Sunnydale', 'sunnydale', 'Cape Town', 'Western Cape'),
  ('Sunset Beach', 'sunset-beach', 'Cape Town', 'Western Cape'),
  ('Tableview', 'table-view', 'Cape Town', 'Western Cape'),
  ('Tamboerskloof', 'tamboerskloof', 'Cape Town', 'Western Cape'),
  ('Thornton', 'thornton', 'Cape Town', 'Western Cape'),
  ('Three Anchor Bay', 'three-anchor-bay', 'Cape Town', 'Western Cape'),
  ('Tokai', 'tokai', 'Cape Town', 'Western Cape'),
  ('Tokai Forest', 'tokai-forest', 'Cape Town', 'Western Cape'),
  ('Tyger Waterfront', 'tyger-waterfront', 'Cape Town', 'Western Cape'),
  ('V&A Waterfront', 'va-waterfront', 'Cape Town', 'Western Cape'),
  ('Valmary Park', 'valmary-park', 'Cape Town', 'Western Cape'),
  ('Van Riebeeckshof', 'van-riebeeckshof', 'Cape Town', 'Western Cape'),
  ('Vredehoek', 'vredehoek', 'Cape Town', 'Western Cape'),
  ('Vredekloof', 'vredekloof', 'Cape Town', 'Western Cape'),
  ('Vredekloof Heights', 'vredekloof-heights', 'Cape Town', 'Western Cape'),
  ('Welgelegen', 'welgelegen', 'Cape Town', 'Western Cape'),
  ('Welgemoed', 'welgemoed', 'Cape Town', 'Western Cape'),
  ('Wellington', 'wellington', 'Wellington', 'Western Cape'),
  ('West Beach', 'west-beach', 'Cape Town', 'Western Cape'),
  ('Westridge', 'westridge', 'Cape Town', 'Western Cape'),
  ('Wetton', 'wetton', 'Cape Town', 'Western Cape'),
  ('Windermere', 'windermere', 'Cape Town', 'Western Cape'),
  ('Woodbridge Island', 'woodbridge-island', 'Cape Town', 'Western Cape'),
  ('Woodstock', 'woodstock', 'Cape Town', 'Western Cape'),
  ('Wynberg', 'wynberg', 'Cape Town', 'Western Cape'),
  ('Ysterplaat', 'ysterplaat', 'Cape Town', 'Western Cape'),
  ('Zevenwacht', 'zevenwacht', 'Cape Town', 'Western Cape'),
  ('Zonnebloem', 'zonnebloem', 'Cape Town', 'Western Cape')
on conflict (slug) do update set
  name = excluded.name,
  city = excluded.city,
  province = excluded.province;
