import { NextResponse } from "next/server";
import { requireAdminSession } from "@/lib/admin/requireAdminSession";
import { compareYmd, todayJohannesburg } from "@/lib/recurring/johannesburgCalendar";
import { firstOccurrenceOnOrAfter, type MonthlyPattern, type RecurringScheduleRow } from "@/lib/recurring/calculateNextRunDate";
import { logSystemEvent } from "@/lib/logging/systemLog";
import { getSupabaseAdmin } from "@/lib/supabase/admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function isIntArrayDays(v: unknown): v is number[] {
  return Array.isArray(v) && v.length > 0 && v.every((x) => typeof x === "number" && x >= 1 && x <= 7);
}

/**
 * Admin: create a recurring schedule row (bookings are generated by cron from `booking_snapshot_template`).
 */
export async function POST(request: Request) {
  const auth = await requireAdminSession(request);
  if (!auth.ok) return auth.response;

  let body: Record<string, unknown>;
  try {
    const raw = await request.json();
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
      return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
    }
    body = raw as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const customer_id = typeof body.customer_id === "string" && body.customer_id.trim() ? body.customer_id.trim() : "";
  const frequency = typeof body.frequency === "string" ? body.frequency : "";
  const start_date = typeof body.start_date === "string" ? body.start_date : "";
  const price = typeof body.price === "number" && Number.isFinite(body.price) ? body.price : NaN;
  const days = body.days_of_week;
  const template = body.booking_snapshot_template;

  if (!customer_id) return NextResponse.json({ error: "customer_id is required." }, { status: 400 });
  if (!["weekly", "biweekly", "monthly"].includes(frequency)) {
    return NextResponse.json({ error: "frequency must be weekly, biweekly, or monthly." }, { status: 400 });
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(start_date)) {
    return NextResponse.json({ error: "start_date must be YYYY-MM-DD." }, { status: 400 });
  }
  if (!isIntArrayDays(days)) {
    return NextResponse.json({ error: "days_of_week must be a non-empty array of integers 1–7 (Mon–Sun)." }, { status: 400 });
  }
  if (!Number.isFinite(price) || price < 0) {
    return NextResponse.json({ error: "price must be a non-negative number." }, { status: 400 });
  }
  if (template === undefined || template === null || (typeof template === "object" && Object.keys(template as object).length === 0)) {
    return NextResponse.json({ error: "booking_snapshot_template is required (v1 snapshot with locked + customer)." }, { status: 400 });
  }

  let monthly_pattern: MonthlyPattern = "mirror_start_date";
  if (body.monthly_pattern === "mirror_start_date" || body.monthly_pattern === "nth_weekday" || body.monthly_pattern === "last_weekday") {
    monthly_pattern = body.monthly_pattern;
  }
  let monthly_nth: number | null = null;
  if (body.monthly_nth === null) {
    monthly_nth = null;
  } else if (typeof body.monthly_nth === "number" && Number.isFinite(body.monthly_nth)) {
    const n = Math.floor(body.monthly_nth);
    if (n >= 1 && n <= 4) monthly_nth = n;
  }
  if (monthly_pattern === "nth_weekday" && monthly_nth == null) {
    return NextResponse.json({ error: "monthly_nth (1–4) is required when monthly_pattern is nth_weekday." }, { status: 400 });
  }

  const end_date =
    body.end_date === null || body.end_date === undefined
      ? null
      : typeof body.end_date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.end_date)
        ? body.end_date
        : null;

  const address_id =
    typeof body.address_id === "string" && body.address_id.trim() ? body.address_id.trim() : null;

  const schedule: RecurringScheduleRow = {
    frequency: frequency as RecurringScheduleRow["frequency"],
    days_of_week: days,
    start_date,
    end_date,
    monthly_pattern,
    monthly_nth,
  };
  const today = todayJohannesburg();
  const anchor = compareYmd(start_date, today) > 0 ? start_date : today;
  const next_run_date =
    typeof body.next_run_date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.next_run_date)
      ? body.next_run_date
      : firstOccurrenceOnOrAfter(schedule, anchor);

  const admin = getSupabaseAdmin();
  if (!admin) return NextResponse.json({ error: "Server configuration error." }, { status: 503 });

  const { data: created, error } = await admin
    .from("recurring_bookings")
    .insert({
      customer_id,
      address_id,
      frequency,
      days_of_week: days,
      start_date,
      end_date,
      price,
      status: "active",
      next_run_date,
      booking_snapshot_template: template,
      monthly_pattern,
      monthly_nth,
    })
    .select("id")
    .maybeSingle();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  const rid = created && typeof created === "object" && "id" in created ? String((created as { id: string }).id) : "";
  if (!rid) return NextResponse.json({ error: "Insert failed." }, { status: 500 });

  await logSystemEvent({
    level: "info",
    source: "admin/recurring/create",
    message: "recurring_booking_created",
    context: { recurring_id: rid, admin_id: auth.user.id, customer_id, frequency },
  });

  return NextResponse.json({ ok: true, id: rid, next_run_date });
}
