-- MASTER-00B-07 — production ledger reconciliation marker.
-- Production recorded a second idempotent application under this timestamp.
-- Intentional no-op: the canonical schema mutation is 20261005010028.
