-- AUDIT-02A01 migration tombstone.
--
-- The original contents of this version enforced the pending-cash guard before all
-- app-required recurring RPCs could be installed and before the compatible writer was live.
-- That ordering is unsafe for a normal pre-deploy migration pass.
--
-- The real repair + CHECK constraint now lives at:
--   supabase/postdeploy/audit-02a01-postdeploy-cash-guard.sql
-- and must be applied only after:
--   1. pre-deploy AUDIT-02A01 RPC migrations are installed;
--   2. the target application release is live and health-verified;
--   3. the post-deploy reconciliation gate is explicitly opened.
--
-- Keep this version as a no-op so environments that have not recorded it can converge
-- migration history without prematurely enforcing the post-deploy invariant.
select 1;
